#!/bin/bash 

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16


gzip -d -c /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879604/SRR3879604_1_bc.fastq.gz | awk '$1 ~ /^@/{{gsub(/.*=/, "", $2)gsub(/.*=/, "", $3);bc=$2$3}{print (bc)}}' > result_extracted_bc/female1.csv
gzip -d -c /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879605/SRR3879605_1_bc.fastq.gz | awk '$1 ~ /^@/{{gsub(/.*=/, "", $2)gsub(/.*=/, "", $3);bc=$2$3}{print (bc)}}' > result_extracted_bc/female2.csv
gzip -d -c /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879606/SRR3879606_1_bc.fastq.gz | awk '$1 ~ /^@/{{gsub(/.*=/, "", $2)gsub(/.*=/, "", $3);bc=$2$3}{print (bc)}}' > result_extracted_bc/female3.csv
